# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/reports.ui'
#
# Created: Wed Nov 21 00:18:24 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(835, 491)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtGui.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.detailed_report = QtGui.QPushButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detailed_report.sizePolicy().hasHeightForWidth())
        self.detailed_report.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.detailed_report.setFont(font)
        self.detailed_report.setStyleSheet("border:0;\n"
"background-color:#757780;\n"
"color:#fff")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/imgs/graph-5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.detailed_report.setIcon(icon)
        self.detailed_report.setIconSize(QtCore.QSize(54, 54))
        self.detailed_report.setObjectName("detailed_report")
        self.horizontalLayout.addWidget(self.detailed_report)
        self.all_report = QtGui.QPushButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_report.sizePolicy().hasHeightForWidth())
        self.all_report.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.all_report.setFont(font)
        self.all_report.setStyleSheet("border:0;\n"
"background-color:#1c3144;\n"
"color:#fff")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imgs/imgs/graph-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.all_report.setIcon(icon1)
        self.all_report.setIconSize(QtCore.QSize(52, 52))
        self.all_report.setFlat(False)
        self.all_report.setObjectName("all_report")
        self.horizontalLayout.addWidget(self.all_report)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.stackedWidget_3 = QtGui.QStackedWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_3.sizePolicy().hasHeightForWidth())
        self.stackedWidget_3.setSizePolicy(sizePolicy)
        self.stackedWidget_3.setStyleSheet("")
        self.stackedWidget_3.setFrameShape(QtGui.QFrame.Box)
        self.stackedWidget_3.setFrameShadow(QtGui.QFrame.Plain)
        self.stackedWidget_3.setLineWidth(0)
        self.stackedWidget_3.setMidLineWidth(0)
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.w1 = QtGui.QWidget()
        self.w1.setStyleSheet(".QWidget{\n"
"background-color: #1c3144;\n"
"color:#fff;\n"
"}\n"
"\n"
"\n"
"")
        self.w1.setObjectName("w1")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.w1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_8 = QtGui.QWidget(self.w1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_5 = QtGui.QWidget(self.widget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_gen = QtGui.QTableWidget(self.widget_5)
        self.tableWidget_gen.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tableWidget_gen.setObjectName("tableWidget_gen")
        self.tableWidget_gen.setColumnCount(7)
        self.tableWidget_gen.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_gen.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_gen.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_gen.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_gen.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_gen.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_gen.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_gen.setHorizontalHeaderItem(6, item)
        self.verticalLayout_3.addWidget(self.tableWidget_gen)
        self.widget_4 = QtGui.QWidget(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pdf_btn = QtGui.QToolButton(self.widget_4)
        self.pdf_btn.setMinimumSize(QtCore.QSize(60, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/imgs/imgs/office-material-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pdf_btn.setIcon(icon2)
        self.pdf_btn.setIconSize(QtCore.QSize(30, 30))
        self.pdf_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pdf_btn.setObjectName("pdf_btn")
        self.horizontalLayout_3.addWidget(self.pdf_btn)
        self.extract_file_btn = QtGui.QToolButton(self.widget_4)
        self.extract_file_btn.setMinimumSize(QtCore.QSize(60, 0))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/imgs/imgs/022-notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.extract_file_btn.setIcon(icon3)
        self.extract_file_btn.setIconSize(QtCore.QSize(30, 30))
        self.extract_file_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.extract_file_btn.setObjectName("extract_file_btn")
        self.horizontalLayout_3.addWidget(self.extract_file_btn)
        self.print_btn = QtGui.QToolButton(self.widget_4)
        self.print_btn.setMinimumSize(QtCore.QSize(60, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/imgs/imgs/037-printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.print_btn.setIcon(icon4)
        self.print_btn.setIconSize(QtCore.QSize(30, 30))
        self.print_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.print_btn.setObjectName("print_btn")
        self.horizontalLayout_3.addWidget(self.print_btn)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.widget_7 = QtGui.QWidget(self.widget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_7)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.date_time_5 = QtGui.QWidget(self.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_time_5.sizePolicy().hasHeightForWidth())
        self.date_time_5.setSizePolicy(sizePolicy)
        self.date_time_5.setObjectName("date_time_5")
        self.gridLayout_8 = QtGui.QGridLayout(self.date_time_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.end_date_gen = QtGui.QDateTimeEdit(self.date_time_5)
        self.end_date_gen.setCalendarPopup(True)
        self.end_date_gen.setObjectName("end_date_gen")
        self.gridLayout_8.addWidget(self.end_date_gen, 1, 1, 1, 1)
        self.st_date_gen = QtGui.QDateTimeEdit(self.date_time_5)
        self.st_date_gen.setCalendarPopup(True)
        self.st_date_gen.setObjectName("st_date_gen")
        self.gridLayout_8.addWidget(self.st_date_gen, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.date_time_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.date_time_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.date_time_5)
        self.line_7 = QtGui.QFrame(self.widget_7)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_6.addWidget(self.line_7)
        self.widget_10 = QtGui.QWidget(self.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_9 = QtGui.QGridLayout(self.widget_10)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_21 = QtGui.QLabel(self.widget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.widget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.widget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.gridLayout_9.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.widget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.gridLayout_9.addWidget(self.label_24, 3, 0, 1, 1)
        self.branch_le_3 = QtGui.QComboBox(self.widget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.branch_le_3.sizePolicy().hasHeightForWidth())
        self.branch_le_3.setSizePolicy(sizePolicy)
        self.branch_le_3.setEditable(True)
        self.branch_le_3.setObjectName("branch_le_3")
        self.gridLayout_9.addWidget(self.branch_le_3, 0, 1, 1, 3)
        self.pushButton = QtGui.QPushButton(self.widget_10)
        self.pushButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/imgs/imgs/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon5)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_9.addWidget(self.pushButton, 0, 4, 1, 1)
        self.service_le_3 = QtGui.QComboBox(self.widget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.service_le_3.sizePolicy().hasHeightForWidth())
        self.service_le_3.setSizePolicy(sizePolicy)
        self.service_le_3.setEditable(True)
        self.service_le_3.setObjectName("service_le_3")
        self.gridLayout_9.addWidget(self.service_le_3, 1, 1, 1, 4)
        self.terminal_le_3 = QtGui.QComboBox(self.widget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminal_le_3.sizePolicy().hasHeightForWidth())
        self.terminal_le_3.setSizePolicy(sizePolicy)
        self.terminal_le_3.setEditable(True)
        self.terminal_le_3.setObjectName("terminal_le_3")
        self.gridLayout_9.addWidget(self.terminal_le_3, 2, 1, 1, 4)
        self.user_le_3 = QtGui.QComboBox(self.widget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_le_3.sizePolicy().hasHeightForWidth())
        self.user_le_3.setSizePolicy(sizePolicy)
        self.user_le_3.setEditable(True)
        self.user_le_3.setObjectName("user_le_3")
        self.gridLayout_9.addWidget(self.user_le_3, 3, 1, 1, 4)
        self.line_8 = QtGui.QFrame(self.widget_10)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_9.addWidget(self.line_8, 4, 0, 1, 5)
        self.verticalLayout_6.addWidget(self.widget_10)
        self.search_btn = QtGui.QToolButton(self.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_btn.sizePolicy().hasHeightForWidth())
        self.search_btn.setSizePolicy(sizePolicy)
        self.search_btn.setStyleSheet("border:0px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/imgs/imgs/024-magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon6)
        self.search_btn.setIconSize(QtCore.QSize(30, 30))
        self.search_btn.setObjectName("search_btn")
        self.verticalLayout_6.addWidget(self.search_btn)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.widget_7)
        self.horizontalLayout_4.addWidget(self.widget_8)
        self.stackedWidget_3.addWidget(self.w1)
        self.w2 = QtGui.QWidget()
        self.w2.setStyleSheet(".QWidget{\n"
"background-color: #757780;\n"
"}")
        self.w2.setObjectName("w2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.w2)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_3 = QtGui.QWidget(self.w2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_6 = QtGui.QWidget(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidget_tm = QtGui.QTableWidget(self.widget_6)
        self.tableWidget_tm.setObjectName("tableWidget_tm")
        self.tableWidget_tm.setColumnCount(3)
        self.tableWidget_tm.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tm.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tm.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tm.setHorizontalHeaderItem(2, item)
        self.verticalLayout_8.addWidget(self.tableWidget_tm)
        self.widget_14 = QtGui.QWidget(self.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setStyleSheet(".QWidget{\n"
"background-color: #fff;\n"
"}\n"
".QLabel\n"
"{\n"
"color:#000;\n"
"}")
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_14)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_15 = QtGui.QWidget(self.widget_14)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_15)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtGui.QLabel(self.widget_15)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_8.addWidget(self.widget_15)
        self.line = QtGui.QFrame(self.widget_14)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        self.widget_9 = QtGui.QWidget(self.widget_14)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_9)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(self.widget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtGui.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_8.addWidget(self.widget_9)
        self.verticalLayout_8.addWidget(self.widget_14)
        self.widget_13 = QtGui.QWidget(self.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_13)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.pdf_btn_2 = QtGui.QToolButton(self.widget_13)
        self.pdf_btn_2.setMinimumSize(QtCore.QSize(60, 0))
        self.pdf_btn_2.setIcon(icon2)
        self.pdf_btn_2.setIconSize(QtCore.QSize(30, 30))
        self.pdf_btn_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pdf_btn_2.setObjectName("pdf_btn_2")
        self.horizontalLayout_5.addWidget(self.pdf_btn_2)
        self.extract_file_btn_2 = QtGui.QToolButton(self.widget_13)
        self.extract_file_btn_2.setMinimumSize(QtCore.QSize(60, 0))
        self.extract_file_btn_2.setIcon(icon3)
        self.extract_file_btn_2.setIconSize(QtCore.QSize(30, 30))
        self.extract_file_btn_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.extract_file_btn_2.setObjectName("extract_file_btn_2")
        self.horizontalLayout_5.addWidget(self.extract_file_btn_2)
        self.print_btn_2 = QtGui.QToolButton(self.widget_13)
        self.print_btn_2.setMinimumSize(QtCore.QSize(60, 0))
        self.print_btn_2.setIcon(icon4)
        self.print_btn_2.setIconSize(QtCore.QSize(30, 30))
        self.print_btn_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.print_btn_2.setObjectName("print_btn_2")
        self.horizontalLayout_5.addWidget(self.print_btn_2)
        self.verticalLayout_8.addWidget(self.widget_13)
        self.horizontalLayout_7.addWidget(self.widget_6)
        self.widget_11 = QtGui.QWidget(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_11)
        self.verticalLayout_7.setContentsMargins(-1, 9, 9, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.date_time_7 = QtGui.QWidget(self.widget_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_time_7.sizePolicy().hasHeightForWidth())
        self.date_time_7.setSizePolicy(sizePolicy)
        self.date_time_7.setObjectName("date_time_7")
        self.gridLayout_10 = QtGui.QGridLayout(self.date_time_7)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.end_date_tm = QtGui.QDateTimeEdit(self.date_time_7)
        self.end_date_tm.setCalendarPopup(True)
        self.end_date_tm.setObjectName("end_date_tm")
        self.gridLayout_10.addWidget(self.end_date_tm, 1, 1, 1, 1)
        self.st_date_tm = QtGui.QDateTimeEdit(self.date_time_7)
        self.st_date_tm.setCalendarPopup(True)
        self.st_date_tm.setObjectName("st_date_tm")
        self.gridLayout_10.addWidget(self.st_date_tm, 0, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.date_time_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.gridLayout_10.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.date_time_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.date_time_7)
        self.line_9 = QtGui.QFrame(self.widget_11)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_7.addWidget(self.line_9)
        self.widget_12 = QtGui.QWidget(self.widget_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_11 = QtGui.QGridLayout(self.widget_12)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.radioButton = QtGui.QRadioButton(self.widget_12)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_11.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.widget_12)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_11.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.widget_12)
        self.search_btn_tm = QtGui.QToolButton(self.widget_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_btn_tm.sizePolicy().hasHeightForWidth())
        self.search_btn_tm.setSizePolicy(sizePolicy)
        self.search_btn_tm.setStyleSheet("border:0px;")
        self.search_btn_tm.setIcon(icon6)
        self.search_btn_tm.setIconSize(QtCore.QSize(30, 30))
        self.search_btn_tm.setObjectName("search_btn_tm")
        self.verticalLayout_7.addWidget(self.search_btn_tm)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_7.addWidget(self.widget_11)
        self.horizontalLayout_6.addWidget(self.widget_3)
        self.stackedWidget_3.addWidget(self.w2)
        self.verticalLayout_2.addWidget(self.stackedWidget_3)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget_3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.detailed_report.setText(QtGui.QApplication.translate("Form", "متوسط الانتظار", None, QtGui.QApplication.UnicodeUTF8))
        self.all_report.setText(QtGui.QApplication.translate("Form", "تقرير مجمل", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_gen.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "رقم العميل", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_gen.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "الخدمة", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_gen.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "الشباك", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_gen.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "المستخدم", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_gen.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "تاريخ الطلب", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_gen.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "تاريخ النداء", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_gen.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "تاريخ الانتهاء", None, QtGui.QApplication.UnicodeUTF8))
        self.pdf_btn.setText(QtGui.QApplication.translate("Form", "PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.extract_file_btn.setText(QtGui.QApplication.translate("Form", "EXCEL", None, QtGui.QApplication.UnicodeUTF8))
        self.print_btn.setText(QtGui.QApplication.translate("Form", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "من", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "الى", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Form", "الفرع", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Form", "الخدمة", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Form", "الشباك", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Form", "المستخدم", None, QtGui.QApplication.UnicodeUTF8))
        self.search_btn.setText(QtGui.QApplication.translate("Form", "بحث", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tm.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "نوع", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tm.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "متوسط الانتظار", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tm.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "متوسط الخدمة", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "متوسط الانتظار", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "متوسط الخدمة", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pdf_btn_2.setText(QtGui.QApplication.translate("Form", "PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.extract_file_btn_2.setText(QtGui.QApplication.translate("Form", "EXCEL", None, QtGui.QApplication.UnicodeUTF8))
        self.print_btn_2.setText(QtGui.QApplication.translate("Form", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Form", "من", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Form", "الى", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("Form", "خدمة", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("Form", "شباك", None, QtGui.QApplication.UnicodeUTF8))
        self.search_btn_tm.setText(QtGui.QApplication.translate("Form", "بحث", None, QtGui.QApplication.UnicodeUTF8))

import source_rc
